
services:
  - docker

sudo: required

# before_install:
  # docker build --tag <tag_name> <current_directory>
  # i.e build the Dockerfile in current directory and give it a tag
  # - docker build -t aakashjangidme/flaskDevops .

script:
  - docker-compose up -d
  - docker-compose ps

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker-compose push