language: python
dist: bionic
os: linux
services:
  - docker

sudo: required

# before_install:
  # docker build --tag <tag_name> <current_directory>
  # i.e build the Dockerfile in current directory and give it a tag
  # - docker build -t aakashjangidme/flaskDevops .

script:
  - docker-compose up -d
  - docker-compose ps
  - docker run -it $DOCKER_ID/flask_devops_python python -m unittest tests/test.py

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker-compose push

deploy:
  provider: elasticbeanstalk
  region: ap-south-1
  app: flask-devops
  env: Flaskdevops-env
  bucket_name: elasticbeanstalk-ap-south-1-863644218407
  bucket_path: flask-devops
  on:
    main
  access-key-id : $ACCESS_KEY
  secret-access-key: $SECRET_KEY