version: '3'

services: 
  api:
    container_name: flaskDevops-python
    image: aakashjangimde/flaskDevopsPython
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    command: gunicorn -b :5000 "run:app"
    volumes: 
      - api_data:/app

  reverse_proxy:
    image: aakashjangimde/flaskDevopsNginx
    container_name: flaskDevops-nginx
    restart: always
    build: ./nginx
    ports: 
      - '80:80'
    depends_on: 
      - api

volumes: 
  api_data: